version: '3.7'
services:
  cqrs:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: relay
    env_file:
      - .env
    tty: true
    ports:
      - "${PORT}:${PORT}"
    restart: always